server:
  port: 8085
  contextPath: /
  address: 0.0.0.0

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.68:3306/tcc_account?useUnicode=true&characterEncoding=utf8
        username: xiaoyu
        password: Wgj@555888


mybatis:
  type-aliases-package: com.hmily.tcc.demo.dubbo.account.api.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        com.hmily.tcc.bonuspoint: info
        com.hmily.tcc.lottery: debug
        com.hmily.tcc: debug
        io.netty: info

    path: "./logs"

